language: node_js
node_js:
    - "6.1"

before_script:
    - cd server
    - npm install -g gulp
    - npm install -g typescript@next
    - npm install -g typings
    - typings install
script: npm run build